FROM nginx:alpine
COPY frontend/dist /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
HEALTHCHECK --interval=15s --timeout=3s --retries=3 CMD wget -qO- http://localhost:80/ || exit 1
